### ISSUE TITLE
Fix config

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Laravel-Segment#1]
The service provider is currently unable to pull out the configuration.

**Comment by jbrooksuk** [comment]
@GrahamCampbell do you know why this is? I can't figure out why the config isn't loaded.

**Comment by GrahamCampbell** [comment]
It's because you haven't setup the package stuff correctly. Let me fix...

**Comment by jbrooksuk** [comment]
Oh?

**Comment by GrahamCampbell** [comment]
You need to add a third param to the package method because laravel doesn't know about PSR-4 by default. That's basically what I've done.

**Comment by jbrooksuk** [comment]
:beer
